#
# Make the code for the 1st task of the Lab
#

CC = gcc
MAKE = mingw32-make

all:
	$(MAKE) clean

	#
	# Compile below
	$(CC) app.c text.c -o app
	
	printf "\n"
	printf "***********\n"
	printf "*** END ***\n"
	printf "***********"
	printf "\n"

clean:
	$(RM) *.exe

.SILENT: all clean